# Generated by Django 3.2.13 on 2022-10-28 06:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
