# Generated by Django 3.2.13 on 2022-10-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
